Add documentation to the module
simontabor/2fa pull request #8
Opened 2019-01-03 14:58 UTC by danielgraycode

I've added some documentation to make it easier for users to understand and use the module.

2019-01-26 13:44 UTC, FozzieHi commented
@simontabor Why isn't this merged?

2019-02-16 14:11 UTC, danielgraycode commented
@simontabor Any update on this? It's been a while and I noticed it still hasn't merged.

2019-02-25 10:49 UTC, simontabor requested changes
Hi Daniel, thanks for the contribution! Sorry for the incredibly slow review - I'd done the review then forgot to submit it. My bad entirely.

There are a few things to be fixed up before we merge. Thanks!

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * @returns A key you can store, check codes and generate QR codes from.
This function doesn't return anything, it accepts another parameter called `cb`

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
>  // get a base36 crypto secure key
may as well remove the old comments now we have lovely JSDoc :)

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * @param counter The time for verifying the code against the key.
missing `opts` param for drift options, if you'd like i can add this

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * let counter = Math.floor(Date.now() / 1000 / 30);
this project is ES5 so probably best to document using `var` for now

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * let validCode = tfa.veryifyHOTP(key, code, counter);
```suggestion
     * var validCode = tfa.verifyHOTP(key, code, counter);
```

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * //Display erorr message
```suggestion
     * // Display error message
```

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * console.log("You can manually enter this code into the authenticator app: " & multikey)
```suggestion
     * console.log('You can manually enter this code into the authenticator app: ' + multikey)
```

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * //Display erorr message
```suggestion
     * // Display error message
```

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * @param key The key generated for the users multifactor.
missing optional opts parameter here

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * @returns An array of backup codes you can store and show the user
calls back, not returns

2019-02-25 10:49 UTC, simontabor commented on lib/2FA.js
> +     * @param pattern The pattern you want the codes to be generated in
Pattern is optional, defaults to `'xxxx-xxxx-xxxx'`

2019-02-25 12:49 UTC, danielgraycode commented
Hi Simon!
Thanks for the suggestions, I’ll work on getting this done and will soon push another commit.

2019-02-25 14:24 UTC, danielgraycode commented
I've changed things according to your feedback, and pushed the commit with these changes.

2019-03-09 16:29 UTC, danielgraycode commented
Any update on this Simon?

2019-03-22 17:34 UTC, danielgraycode commented
??

2019-04-07 09:30 UTC, simontabor approved these changes

2019-04-07 09:30 UTC, merged

2019-04-07 09:31 UTC, simontabor commented
Merged! @danielgraycode sorry for taking so long to do this, really appreciate the contribution!